### ISSUE TITLE
Run pyspark example

### ISSUE THREAD

**Issue by p9anand** [sbakiu/kubeflow-spark#2]
Hey i was trying to implement the same for the pyspark using yaml provided in the example. https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/examples/spark-py-pi.yaml.

But getting following errors.
`++ id -u
+ myuid=185
++ id -g
+ mygid=0
+ set +e
++ getent passwd 185
+ uidentry=
+ set -e
+ '[' -z '' ']'
+ '[' -w /etc/passwd ']'
+ echo '185:x:185:0:anonymous uid:/opt/spark:/bin/false'
+ SPARK_CLASSPATH=':/opt/spark/jars/*'
+ grep SPARK_JAVA_OPT_
+ env
+ sort -t_ -k4 -n
+ sed 's/[^=]*=\(.*\)/\1/g'
+ readarray -t SPARK_EXECUTOR_JAVA_OPTS
+ '[' -n '' ']'
+ '[' -z ']'
+ '[' -z ']'
+ '[' -n '' ']'
+ '[' -z ']'
+ '[' -z x ']'
+ SPARK_CLASSPATH='/opt/spark/conf::/opt/spark/jars/*'
+ case "$1" in
+ echo 'Non-spark-on-k8s command provided, proceeding in pass-through mode...'
+ CMD=("$@")
+ exec /usr/bin/tini -s -- driver-py --properties-file /opt/spark/conf/spark.properties --class org.apache.spark.deploy.PythonRunner
Non-spark-on-k8s command provided, proceeding in pass-through mode...
[FATAL tini (16)] exec driver-py failed: No such file or directory`

**Comment by sbakiu** [comment]
Hey @p9anand, can you share how you are running the manifest file?

**Comment by p9anand** [comment]
Below is the yaml file. In python file i have just made changes in the loading the below YAML file, rest is same. 

`
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: pyspark-pi
  namespace: v1-satish
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "gcr.io/spark-operator/spark-py:v3.1.1"
  imagePullPolicy: Always
  mainApplicationFile: local:///opt/spark/examples/src/main/python/pi.py
  sparkVersion: "3.1.1"
  restartPolicy:
    type: OnFailure
    onFailureRetries: 3
    onFailureRetryInterval: 10
    onSubmissionFailureRetries: 5
    onSubmissionFailureRetryInterval: 20
  driver:
    annotations:
      "sidecar.istio.io/inject": "false"
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.1
    serviceAccount: spark
  executor:
    annotations:
      "sidecar.istio.io/inject": "false"
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.1.1
`

**Comment by sbakiu** [comment]
Just tested with the python manifest file and I had to make a few changes:

- https://github.com/sbakiu/kubeflow-spark/blob/main/spark-job-python.yaml#L22 add `-{epoch}` to make sure the sparkApplication name is not repeated
- https://github.com/sbakiu/kubeflow-spark/blob/main/spark-job-python.yaml#L23 - make sure it is the same namespace where kubeflow is installed
- https://github.com/sbakiu/kubeflow-spark/blob/main/spark-job-python.yaml#L44 - make sure it is the same SA name as the one created in https://github.com/sbakiu/kubeflow-spark/blob/main/scripts/spark-rbac.yaml#L4

Afterward, run `python kubeflow_pipeline.py` and upload the generated `spark_job_pipeline.yaml` in the Kubeflow Pipelines UI. The execution should work.

**Comment by p9anand** [comment]
Thanks for the response. I tried with your suggested changes. In our case we are using multi-tenancy so, https://github.com/sbakiu/kubeflow-spark/blob/main/spark-job-python.yaml#L23
we are using our own namespace. and "spark" namespace which created in https://github.com/sbakiu/kubeflow-spark/blob/main/scripts/spark-rbac.yaml#L4.
But i'm getting the same error.

**Comment by sbakiu** [comment]
The error you are seeing might be related to the way spark-operator is installed. I would recommend to check with the documentation [here](https://github.com/GoogleCloudPlatform/spark-on-k8s-operator/blob/master/docs/design.md).
